apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cou5jac-b-python
  janus-idp.io/tekton: cou5jac-b-python
  backstage.io/kubernetes-id: cou5jac-b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cou5jac-b-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
